version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_rag
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage

  ollama:
    image: ollama/ollama:latest
    container_name: ollama_rag
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama

  api-go:
    build:
      context: ./api-go
    container_name: go_api_gateway
    ports:
      - "8080:8080"
    depends_on:
      - qdrant
      - ollama