from pathlib import Path
from typing import Protocol


class ObjectStorage(Protocol):
    def download(self, bucket: str, object_key: str, destination: Path) -> None: ...

    def list_buckets(self) -> list[str]: ...

    def list_object_keys(self, bucket: str) -> list[str]: ...

    def upload(self, bucket: str, object_key: str, source: object, length: int, content_type: str) -> None: ...